use_frameworks!

platform :ios, '9.0'

target 'AZNavigationPopSwiper_Example' do
  pod 'AZNavigationPopSwiper', :path => '../'

  target 'AZNavigationPopSwiper_Tests' do
    inherit! :search_paths

    
  end
end
